version: '3.9'

services:

  backend:                                      #THE BACKEND SIDE OF OUR APP ITSELF :
    build:
      context: ./back 
      #dockerfile: ./back/Dockerfile
      #target: dev #for multi stage
    env_file:
      - ./env/back.env
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
    networks:
      - backend
    depends_on:
      - database
    restart: unless-stopped
  
  database:                                      #THE POSTGRESQL DATABASE
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    environment:
      POSTGRES_USER: transcendeur
      POSTGRES_PASSWORD: bigData
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data

  databaseadmin:                                 #THE DATABASE 'ADMIN GRAPHICAL INTERFACE'
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 5050:80
    env_file:
      - ./env/pgadmin.env
    environment:
      PGADMIN_DEFAULT_EMAIL: nidma@nidma.com
      PGADMIN_DEFAULT_PASSWORD: dimnagp4
    networks:
      - backend
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - database

  # frontend:                                       #THE FRONTEND SIDE OF OUR APP ITSELF :
  #   build:
  #     dockerfile: front/Dockerfile
  #   env_file:
  #     - ./env/front.env
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  #   networks:
  #     - backend
  #   volumes:
  #     - ./front:/app
  #   depends_on:
  #     - backend
    

volumes:
  data:

networks:
  backend: